name: Rust Code Check

on:
    pull_request:
        types: [opened, synchronize, reopened]

jobs:
  cargo-check:
    name: Cargo Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Install wasm32-unknown-unknown target
        run: rustup target add wasm32-unknown-unknown
        
      - name: Run Cargo Check
        run: cargo check --target=wasm32-unknown-unknown
